const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
window.addEventListener('load',()=>setTimeout(()=>$('.loader')?.classList.add('done'),650));
const progress=$('.progress span');
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max?scrollY/max*100:0)+'%';},{passive:true});
if(matchMedia('(pointer:fine)').matches){const c=$('.cursor');addEventListener('pointermove',e=>{c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'},{passive:true});$$('a,button,.project-visual,.magnetic').forEach(el=>{el.addEventListener('mouseenter',()=>{c.style.width='54px';c.style.height='54px'});el.addEventListener('mouseleave',()=>{c.style.width='34px';c.style.height='34px'})})}
const revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12});$$('.reveal,.project,.process-card,.about-visual,.about-copy').forEach(el=>revealObserver.observe(el));
const metricObserver=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return; const el=e.target; const target=Number(el.dataset.count||0); if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=target+'+'; metricObserver.unobserve(el); return;} const start=performance.now(); const duration=1100; const tick=now=>{const p=Math.min(1,(now-start)/duration); const eased=1-Math.pow(1-p,3); el.textContent=Math.round(target*eased)+'+'; if(p<1) requestAnimationFrame(tick); else metricObserver.unobserve(el)}; requestAnimationFrame(tick)}),{threshold:.7}); $$('.metric-number').forEach(el=>metricObserver.observe(el));
// magnetic controls
if(matchMedia('(pointer:fine)').matches){$$('.magnetic').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;el.style.transform=`translate(${x*.12}px,${y*.12}px)`}));$$('.magnetic').forEach(el=>el.addEventListener('pointerleave',()=>el.style.transform=''))}
// project previews
$$('.project').forEach(p=>{const v=p.querySelector('video');p.addEventListener('mouseenter',()=>v.play().catch(()=>{}));p.addEventListener('mouseleave',()=>{v.pause();try{v.currentTime=0}catch{}});p.querySelector('.project-visual').addEventListener('click',()=>openViewer(p))});
const modal=$('#videoModal'),mv=$('#modalVideo'),frame=$('#viewerFrame'),seek=$('#seek'),time=$('#time'),title=$('#viewerTitle'),type=$('#viewerType'),play=$('#togglePlay'),big=$('#bigPlay'),mute=$('#mute'),fs=$('#fs');
const fmt=s=>{if(!isFinite(s))return'0:00';return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0')};
function openViewer(p){modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');mv.src=p.dataset.video;title.textContent=p.dataset.title;type.textContent=p.dataset.type;seek.value=0;time.textContent='0:00';mute.textContent='MUTED';mv.load();mv.play().catch(()=>{});update()}
function closeViewer(){mv.pause();mv.removeAttribute('src');mv.load();modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{})}
function update(){const on=!mv.paused;play.textContent=on?'PAUSE':'PLAY';frame.classList.toggle('playing',on)}
function toggle(){mv.paused?mv.play().catch(()=>{}):mv.pause()}
play.onclick=toggle;big.onclick=toggle;mv.onplay=update;mv.onpause=update;mv.ontimeupdate=()=>{seek.value=mv.duration?mv.currentTime/mv.duration*100:0;time.textContent=fmt(mv.currentTime)};seek.oninput=()=>{if(mv.duration)mv.currentTime=mv.duration*seek.value/100};mute.onclick=()=>{mv.muted=!mv.muted;mute.textContent=mv.muted?'MUTED':'SOUND'};$('#closeBtn').onclick=closeViewer;$('.modal-backdrop').onclick=closeViewer;
fs.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await frame.requestFullscreen()}catch{}};document.addEventListener('fullscreenchange',()=>fs.textContent=document.fullscreenElement?'EXIT':'FULL');document.addEventListener('keydown',e=>{if(modal.classList.contains('open')){if(e.key==='Escape')closeViewer();if(e.key===' '&&e.target.tagName!=='INPUT'){e.preventDefault();toggle()}}});
// subtle parallax for hero art
if(matchMedia('(pointer:fine)').matches){const art=$('.hero-art');addEventListener('pointermove',e=>{const x=(e.clientX-innerWidth/2)/innerWidth,y=(e.clientY-innerHeight/2)/innerHeight;art.style.transform=`translate(${x*8}px,${y*8}px)`},{passive:true})}
